name: integration-test-1

on:
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    run-inference:
        runs-on: ubuntu-latest

        steps:

            # - name: setup SSH
            #   uses: webfactory/ssh-agent@v0.9.0
            #   with:
            #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - run: touch ./tst
            - run: ls
            
            - name: setup
              run: echo -n ${{ secrets.SSH_PRIVATE_KEY }} > ./mrt

            - name: run inference
              run: ssh -i ./mrt root@52.118.207.5 "python3 /my.py"
