name: integration-test-1

on:
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    run-inference:
        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v4

            - name: upload test case
              uses: betanzos/scp-upload@v1.1.0
              with:
                host: ${{ secrets.TEST_VM }}
                username: ${{ secrets.TEST_VM_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                source: './tests/agra/test_1.py'
                remote_dir: '/opt'
                recursive: 'false'

            - name: run test case
              uses: appleboy/ssh-action@v1.2.0
              with  :
                host: ${{ secrets.TEST_VM }}
                username: ${{ secrets.TEST_VM_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  python3 -m venv /opt/.venv-test
                  source /opt/.venv-test/bin/activate
                  pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl
  
            - name: run test case
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: ${{ secrets.TEST_VM }}
                username: ${{ secrets.TEST_VM_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  # source /opt/.venv-test/bin/activate
                  python3 /opt/test_1.py
