name: integration-test-1

on:
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    run-inference:
        runs-on: ubuntu-latest

        steps:

            - uses: appleboy/ssh-action
              with:
                host: ${{ secrets.TEST_VM }}
                username: ${{ secrets.TEST_VM_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    python3 /my.py
