name: integration-test-1
run-name: ${{ github.actor }} is learning GitHub Actions
on:
    pull_request:
        types: [opened,edited]
jobs:
    run-inference:
        runs-on: ubuntu-latest
        steps:
            - uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - run: ssh root@${{ secrets.TEST_VM }} "python3 /my.py"
